########################(beg of [Makefile])########################
Library=./../..
###################################################################

comp::

###################################################################

clean:: ; rm -f *~

cleanall:: clean
cleanall:: ; rm -f *.class

###################################################################

comp:: ; javac -cp $(Library) FnList.java
comp:: ; javac -cp $(Library) FnListUtil.java
comp:: ; javac -cp $(Library) FnListSUtil.java

########################(end of [Makefile])########################
