############################################################
JAVA=java
JAVAC=javac
MYCPATH=.::./../Code/Library.jar
############################################################

all::

############################################################

clean: ; rm -f *~
cleanall: clean
cleanall: ; rm -f *.class

############################################################

all:: \
Assign06_01
Assign06_01: \
Assign06_01.class; \
$(JAVA) -cp $(MYCPATH) Assign06_01
Assign06_01.class: \
Assign06_01.java ; \
$(JAVAC) -cp $(MYCPATH) Assign06_01.java

############################################################

all:: \
Assign06_02
Assign06_02: \
Assign06_02.class; \
$(JAVA) -cp $(MYCPATH) Assign06_02
Assign06_02.class: \
Assign06_02.java ; \
$(JAVAC) -cp $(MYCPATH) Assign06_02.java

############################################################

all:: \
Assign06_03
Assign06_03: \
Assign06_03.class; \
$(JAVA) -cp $(MYCPATH) Assign06_03
Assign06_03.class: \
Assign06_03.java ; \
$(JAVAC) -cp $(MYCPATH) Assign06_03.java

############################################################
